apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  # To encode: echo -n "your-password" | base64
  
  # Database credentials
  DB_USERNAME: <BASE64_ENCODED_DB_USERNAME>  # Example: postgres
  DB_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>  # Example: your-secure-password
  
  # JWT secret for authentication
  JWT_SECRET: <BASE64_ENCODED_JWT_SECRET>  # Example: your-super-secret-jwt-key
  
  # Payment gateway API key (Stripe)
  STRIPE_SECRET_KEY: <BASE64_ENCODED_STRIPE_KEY>  # Example: sk_test_your_stripe_key
  
  # Email credentials (optional)
  SMTP_USERNAME: <BASE64_ENCODED_EMAIL>  # Example: your-email@domain.com
  SMTP_PASSWORD: <BASE64_ENCODED_EMAIL_PASSWORD>  # Example: your-app-password
  
  # Redis password (optional)
  REDIS_PASSWORD: <BASE64_ENCODED_REDIS_PASSWORD>  # Example: your-redis-password

# Instructions:
# 1. Copy this file to secrets.yaml
# 2. Replace all <BASE64_ENCODED_*> placeholders with actual base64 encoded values
# 3. To encode a value: echo -n "your-value" | base64
# 4. Never commit the actual secrets.yaml file to git
